-- 创建会话临时表用于数据处理
DECLARE GLOBAL TEMPORARY TABLE SESSION.#TABLE_TMP (
ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20),
COL1 VARCHAR(20),
COLNAME VARCHAR(100)
) NOT LOGGED WITH REPLACE ON COMMIT PRESERVE ROWS;
-- NOT LOGGED 不记录日志
-- WITH REPLACE 是程序结束后删除该临时表，即可重复创建
-- on commit delete rows用于事务相关,也就在事务结束后truncate data in the temporary table，删除数据？
-- on commit preserve rows表示在会话结束后清除临时表的数据

DECLARE GLOBAL TEMPORARY TABLE SESSION.#TABLE_TMP 
LIKE TABLENAME INCLUDING COLUMN DEFAULTS WITH REPLACE ON COMMIT PRESERVE ROWS;
-- 以TABLENAME表结构创建临时表